
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: source ./myvenv/bin/activate
      - run: pip install django
      - run: python manage.py runserver

workflows:
  version: 2
  build:
    jobs:
      - build
